stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  image: node:latest
  tags:
    - react
    - ts
  script:
    - npm install
    - npm run build
  after_script:
    - 'curl -X POST -H "Content-Type: application/json" -d {"content":"Deployment finished: $CI_COMMIT_REF_NAME ($CI_COMMIT_SHORT_SHA)"} https://discord.com/api/webhooks/1181227021163040818/sKPSiLJRfNUGswoa7HuBwZ1HiSIf7j7lidtKNN9j0SP_mjCjboExv70ARh5Ypom6rCVg'
  artifacts:
    paths:
      - dist/

lint-test-job:
  stage: test
  image: node:latest
  tags:
    - react
    - ts
  script:
    - npm install
    - npm run lint
   after_script:
    - 'curl -X POST -H "Content-Type: application/json" -d {"content":"Deployment finished: $CI_COMMIT_REF_NAME ($CI_COMMIT_SHORT_SHA)"} https://discord.com/api/webhooks/1181227021163040818/sKPSiLJRfNUGswoa7HuBwZ1HiSIf7j7lidtKNN9j0SP_mjCjboExv70ARh5Ypom6rCVg'

deploy-job:
  stage: deploy
  tags:
    - deploy
  script:
    - npm install
    - npm run preview
   after_script:
    - 'curl -X POST -H "Content-Type: application/json" -d {"content":"Deployment finished: $CI_COMMIT_REF_NAME ($CI_COMMIT_SHORT_SHA)"} https://discord.com/api/webhooks/1181227021163040818/sKPSiLJRfNUGswoa7HuBwZ1HiSIf7j7lidtKNN9j0SP_mjCjboExv70ARh5Ypom6rCVg'
