stages:
  - build
  - test

build-job:
  stage: build
  image: node:latest
  tags:
    - react
    - ts
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

lint-test-job:
  stage: test
  image: node:latest
  script:
    - npm install
    - npm run lint
