stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  image: node:latest
  tags:
    - react
    - ts
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

lint-test-job:
  stage: test
  image: node:latest
  tags:
    - react
    - ts
  script:
    - npm install
    - npm run lint

deploy-job:
  stage: deploy
  tags:
    - deploy
  script:
    - npm install
    - npm run preview
    - apk add --update git curl
    - wget https://raw.githubusercontent.com/DiscordHooks/gitlab-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - /bin/ash ./send.sh success $WEBHOOK_URL
