stages:
  - build
  - linter
  - deploy
  - release
  - rollback

.node_image:
  image: node:latest

include:
  - local: build.yml
  - local: linter.yml
  - local: deploy.yml
  - local: release.yml
  - local: rollback.yml
