stages:
  - build
  - test
  - deploy

variables:
  DISCORD_WEBHOOK: "https://discord.com/api/webhooks/1181227021163040818/sKPSiLJRfNUGswoa7HuBwZ1HiSIf7j7lidtKNN9j0SP_mjCjboExv70ARh5Ypom6rCVg"

build-job:
  stage: build
  image: node:latest
  tags:
    - react
    - ts
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

lint-test-job:
  stage: test
  image: node:latest
  tags:
    - react
    - ts
  script:
    - npm install
    - npm run lint

deploy-job:
  stage: deploy
  tags:
    - deploy
  script:
    - npm install
    - npm run preview &
    - 'curl -X POST -H "Content-type: application/json" --data ''{"content":"Deployment job completed!"}'' $DISCORD_WEBHOOK'
  needs:
    - build-job
    - test-job