stages:
  - build
  - test

build-job:
  stage: build
  image: node:latest
  script:
    - npm install
    - npm run build

lint-test-job:
  stage: test
  image: node:latest
  script:
    - npm install
    - npm run lint
