stages:
  - install
  - build
  - test
  - deploy

.install:
  image: node:latest
  stage: install

build-job:
  stage: build
  extends: .install
  tags:
    - react
    - ts
  only:
    changes:
      - "src/"
  script:
    - echo "Start build"
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

lint-test-job:
  stage: test
  extends: .install
  tags:
    - react
    - ts
  script:
    - echo "Lint"
    - npm install
    - npm run lint

deploy-job:
  stage: deploy
  extends: .install
  tags:
    - deploy
  script:
    - npm install
    - npm run preview &
    - 'curl -X POST -H "Content-type: application/json" --data ''{"content":"Deployment job completed!"}'' $DISCORD_WEBHOOK'
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - exists:
        - $DISCORD_WEBHOOK
  needs:
    - lint-test-job

releases:
  stage: deploy
  script:
    - echo "Creating release $CI_COMMIT_TAG"
    - curl --request POST --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" --data "tag_name=$CI_COMMIT_TAG" "https://gitlab.kupriyanov.space/NikitaNefyodov/delivery-service.git/api/v4/projects/$CI_PROJECT_ID/releases"
