build-job:
  stage: build
  tags:
    - react
    - ts
  script:
    - echo "Start build $CI_REGISTRY_USER"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/test_project:v0.$CI_PIPELINE_IID .
    - docker push $CI_REGISTRY_IMAGE/test_project:v0.$CI_PIPELINE_IID
  artifacts:
    paths:
      - dist/
